apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: bitbucket-listener
      interceptors:
        - ref:
            name: "bitbucket"
          params:
            - name: "eventTypes"
              value:
                - repo:refs_changed  
      bindings:
        - ref: bitbucket-binding 
      template:
        ref: bitbucket-template
